version: 2.1

jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run test
  afterTests1:
    machine: true
    steps:
      - run: echo "tests 1 have passed!"
  afterTests2:
    machine: true
    steps:
      - run: echo "tests 2 have passed!"
  deploy:
    machine: true
    steps:
      - run: echo "deploy"
workflows:
  build:
    jobs:
      - checkout_and_unit_test
      - deploy_backend:
        requires:
         - checkout_and_unit_test
      - integration_tests_backend:
        requires:
         - deploy_backend
      - deploy_staging:
        requires:
        -integration_tests_backend
      - acceptance_tests_1:
          requires:
            - deploy_staging
      - acceptance_tests_2:
          requires:
            - deploy_staging
      - acceptance_tests_3:
          requires:
            - deploy_staging
      - acceptance_tests_4:
          requires:
            - deploy_staging
      - deploy_staging:
          requires:
            - acceptance_tests_1
            - acceptance_tests_2
            - acceptance_tests_3
            - acceptance_tests_4
