version: 2.1

jobs:
  checkout_and_unit_test:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run test
  acceptance_tests_1:
    machine: true
    steps:
      - run: echo "tests 1 have passed!"
  acceptance_tests_2:
    machine: true
    steps:
      - run: echo "tests 2 have passed!"
  acceptance_tests_3:
    machine: true
    steps:
      - run: echo "tests 3 have passed!"
  acceptance_tests_4:
    machine: true
    steps:
      - run: echo "tests 4 have passed!"
  deploy_production:
    machine: true
    steps:
      - run: echo "deploy production"
workflows:
  build:
    jobs:
      - checkout_and_unit_test
      - acceptance_tests_1:
          requires:
            - checkout_and_unit_test
      - acceptance_tests_2:
          requires:
            - checkout_and_unit_test
      - acceptance_tests_3:
          requires:
            - checkout_and_unit_test
      - acceptance_tests_4:
          requires:
            - checkout_and_unit_test
      - deploy_production:
          requires:
            - acceptance_tests_1
            - acceptance_tests_2
            - acceptance_tests_3
            - acceptance_tests_4
